// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATtBG0QVTCQ6Ijuj02ttiC-GnTzcEL3i0',
    appId: '1:358480996198:web:e68017e7e81b5b82d24aa7',
    messagingSenderId: '358480996198',
    projectId: 'fir-demo-e0871',
    authDomain: 'fir-demo-e0871.firebaseapp.com',
    storageBucket: 'fir-demo-e0871.appspot.com',
    measurementId: 'G-0PDY3C7YX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn2DbpauPUS16TxdVlrLqhjfb_8wdB7eo',
    appId: '1:358480996198:android:21b3c4ae9863e7c7d24aa7',
    messagingSenderId: '358480996198',
    projectId: 'fir-demo-e0871',
    storageBucket: 'fir-demo-e0871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3inAwmwHfMjzEcm7XhnTHP097_W6I-z8',
    appId: '1:358480996198:ios:86d142a0f67f5d1bd24aa7',
    messagingSenderId: '358480996198',
    projectId: 'fir-demo-e0871',
    storageBucket: 'fir-demo-e0871.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3inAwmwHfMjzEcm7XhnTHP097_W6I-z8',
    appId: '1:358480996198:ios:86d142a0f67f5d1bd24aa7',
    messagingSenderId: '358480996198',
    projectId: 'fir-demo-e0871',
    storageBucket: 'fir-demo-e0871.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATtBG0QVTCQ6Ijuj02ttiC-GnTzcEL3i0',
    appId: '1:358480996198:web:1b119fb2f2dfb683d24aa7',
    messagingSenderId: '358480996198',
    projectId: 'fir-demo-e0871',
    authDomain: 'fir-demo-e0871.firebaseapp.com',
    storageBucket: 'fir-demo-e0871.appspot.com',
    measurementId: 'G-PW008SHSH1',
  );
}
